# Generated by Django 2.1.3 on 2018-12-10 13:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankaccoount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Money', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_see_bankaccount', 'View a bancaccount'), ('can_change_bankaccount', 'Can change a bankaccount'), ('can_delete_bankaccount', 'Can delete a bankaccount')),
            },
        ),
    ]
