# Generated by Django 2.1.3 on 2018-12-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccoount',
            options={'permissions': (('can_see_bankaccount', 'View a bancaccount'), ('can_change_bankaccount', 'Can change a bankaccount'), ('can_delete_bankaccount', 'Can delete a bankaccount'), ('can_abheben', 'Kann ein Abheben von einem Bankaccount'), ('can_einzahlen', 'Kann ein Abheben von einem Bankaccount'), ('can_bankeröffnung', 'Kann ein Bankacccount eröffnen'), ('can_payafriend', 'Kann ein Geld an einen Freund senden'))},
        ),
    ]
