# Generated by Django 2.1.3 on 2018-12-15 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankaccount', '0002_auto_20181215_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorname', models.CharField(max_length=60)),
                ('Nachname', models.CharField(max_length=60)),
                ('Antragswunsch', models.CharField(max_length=60)),
                ('Kontotyp', models.CharField(max_length=60)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaktion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.PositiveIntegerField(default=1)),
                ('Money_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_account', to='bankaccount.Bankaccoount')),
                ('Money_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_account', to='bankaccount.Bankaccoount')),
            ],
        ),
    ]
