# Generated by Django 2.1.4 on 2018-12-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0003_antrag_transaktion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaktion',
            name='Value',
            field=models.FloatField(default=1),
        ),
    ]
