# Generated by Django 2.1.4 on 2018-12-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0006_auto_20181217_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccoount',
            name='Money_currency',
        ),
        migrations.RemoveField(
            model_name='transaktion',
            name='Value_currency',
        ),
        migrations.AlterField(
            model_name='bankaccoount',
            name='Money',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaktion',
            name='Value',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
    ]
